// <auto-generated />
using System;
using BTAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTAS.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220312043704_ModifySettingsTable2")]
    partial class ModifySettingsTable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_contact_details", b =>
                {
                    b.Property<int>("idtbl_client_contact_details")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("tbl_client_contact_details_active")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_client_contact_details_email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_contact_details_first_name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_contact_details_last_name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_contact_details_position")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_contact_details_tel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_contact_details_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_client_header_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_client_contact_details");

                    b.HasIndex("tbl_client_header_id");

                    b.ToTable("tbl_client_contact_details");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_contact_group", b =>
                {
                    b.Property<int>("idtbl_client_contact_group")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("tbl_client_contact_group_active")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_contact_group_default")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("tbl_client_contact_group_number")
                        .HasColumnType("int");

                    b.HasKey("idtbl_client_contact_group");

                    b.ToTable("tbl_client_contact_group");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_header", b =>
                {
                    b.Property<int>("idtbl_client_header")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_client_header_abn")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_client_header_active")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_client_header_address1")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_client_header_address2")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_client_header_city")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_closest_port")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_country")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_client_header_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("tbl_client_header_created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("tbl_client_header_is_agent")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_broker")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_carrier")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_consignee")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_consignor")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_payable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_client_header_is_receivable")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_client_header_main_contact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_main_email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_main_phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_postcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_state")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_client_header_suburb")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("tbl_hawb_id")
                        .HasColumnType("int");

                    b.Property<int>("tbl_hawb_incoterms_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_mawb_carrier_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_mawb_creditor_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_mawb_destination_id")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_mawb_origin_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_client_header");

                    b.HasIndex("tbl_hawb_id");

                    b.HasIndex("tbl_hawb_incoterms_id");

                    b.HasIndex("tbl_mawb_carrier_id");

                    b.HasIndex("tbl_mawb_creditor_id");

                    b.HasIndex("tbl_mawb_destination_id");

                    b.HasIndex("tbl_mawb_origin_id");

                    b.ToTable("tbl_client_header");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_container", b =>
                {
                    b.Property<int>("idtbl_container")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("tbl_container_createdDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("tbl_container_grossWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_container_mode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("tbl_container_qty")
                        .HasColumnType("int");

                    b.Property<string>("tbl_container_sealNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_container_sealedBy")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_container_type")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("tbl_mawb_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_container");

                    b.HasIndex("tbl_mawb_id");

                    b.ToTable("tbl_container");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_default_settings", b =>
                {
                    b.Property<int>("idtbl_default_settings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isBillTo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("tbl_address_type")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("tbl_contact_group_id")
                        .HasColumnType("int");

                    b.Property<bool>("tbl_default_settings_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("tbl_incoterm_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_default_settings");

                    b.ToTable("tbl_default_settings");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb", b =>
                {
                    b.Property<int>("idtbl_hawb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("tbl_container_id")
                        .HasColumnType("int");

                    b.Property<byte>("tbl_hawb_DG")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_hawb_FTA")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_hawb_UN")
                        .HasColumnType("longtext");

                    b.Property<string>("tbl_hawb_airJobReference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_class")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_clearancedate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_coloaderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_hawb_coo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_hawb_currency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_deliveryInstructions")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("tbl_hawb_deliverydate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_hawb_description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_hawb_destinationAirport")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_incotermCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_hawb_incoterms_id")
                        .HasColumnType("int");

                    b.Property<string>("tbl_hawb_latestTracking")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_originAirport")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_packaging")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_hawb_pieces")
                        .HasColumnType("int");

                    b.Property<string>("tbl_hawb_service")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_shipperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_shipperRef")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_hawb_tailLiftD")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_hawb_tailLiftO")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("tbl_hawb_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_hawb_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_hawb_value")
                        .HasColumnType("int");

                    b.Property<decimal>("tbl_hawb_volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tbl_hawb_weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("tbl_mawb_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_hawb");

                    b.HasIndex("tbl_container_id");

                    b.HasIndex("tbl_hawb_incoterms_id");

                    b.HasIndex("tbl_mawb_id");

                    b.ToTable("tbl_hawb");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb_incoterms", b =>
                {
                    b.Property<int>("idtbl_hawb_incoterms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_hawb_incoterms_code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_incoterms_description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("idtbl_hawb_incoterms");

                    b.ToTable("tbl_hawb_incoterms");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb_items", b =>
                {
                    b.Property<int>("idtbl_hawb_items")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("tbl_hawb_id")
                        .HasColumnType("int");

                    b.Property<string>("tbl_hawb_items_description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("tbl_hawb_items_dg")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("tbl_hawb_items_height")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_hawb_items_lenghtUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_hawb_items_length")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("tbl_hawb_items_qty")
                        .HasColumnType("int");

                    b.Property<string>("tbl_hawb_items_reference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_hawb_items_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_hawb_items_weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_hawb_items_weightUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_hawb_items_width")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("idtbl_hawb_items");

                    b.HasIndex("tbl_hawb_id");

                    b.ToTable("tbl_hawb_items");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_items_sku", b =>
                {
                    b.Property<int>("idtbl_items_sku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_items_batchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_items_batteryPacking")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_items_batteryType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_items_dangerousGoods")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_items_description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_items_dimensionUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_items_height")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_items_hsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_items_length")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_items_nativeDescription")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("tbl_items_number")
                        .HasColumnType("int");

                    b.Property<string>("tbl_items_originCountry")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_items_productUrl")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_items_skuCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_items_value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("tbl_items_volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tbl_items_weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_items_weightUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_items_width")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("idtbl_items_sku");

                    b.ToTable("tbl_items_sku");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_mawb", b =>
                {
                    b.Property<int>("idtbl_mawb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_mawb_bookingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_mawb_containerMode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_mawb_masterBillNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_mawb_transportType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_mawb_type")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("tbl_mawb_voyage_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_mawb");

                    b.HasIndex("tbl_mawb_voyage_id");

                    b.ToTable("tbl_mawb");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_parcel_info", b =>
                {
                    b.Property<int>("idtbl_parcel_info")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_parcel_info_abnnumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_parcel_info_authorityToLeave")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_parcel_info_batchId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_parcel_info_coveramount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_parcel_info_deliveryAddressLine1")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_deliveryAddressLine2")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_deliveryAddressLine3")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_deliveryCity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryCompany")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryContact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryContactEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryCountry")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("tbl_parcel_info_deliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_parcel_info_deliveryEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryInstructions")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryPostcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliveryState")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_deliverySuburb")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("tbl_parcel_info_dg")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_parcel_info_dgClass")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_dgPackaging")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_dgUn")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_facility")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_parcel_info_gstexemptioncode")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_parcel_info_incoterm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_instruction")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_invoiceCurrency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_parcel_info_invoiceValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("tbl_parcel_info_lockerService")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_parcel_info_nativeDescription")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_orderItems")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_parcelItems")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_platform")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("tbl_parcel_info_readyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_parcel_info_referenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnAddress1")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_returnAddress2")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_returnAddress3")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_returnCity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnCountry")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnOption")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnPostcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_returnState")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_serviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_serviceOption")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipment")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperAddressLine1")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_shipperAddressLine2")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_shipperAddressLine3")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_shipperCity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperCompany")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperContact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperCountry")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperInstructions")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_info_shipperLastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperPostcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperState")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_shipperSuburb")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_sortCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("tbl_parcel_info_tailLiftD")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("tbl_parcel_info_tailLiftO")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("tbl_parcel_info_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_parcel_info_trackingNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_vendorid")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_info_warehouse")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_receptacle_id")
                        .HasColumnType("int");

                    b.HasKey("idtbl_parcel_info");

                    b.HasIndex("tbl_receptacle_id");

                    b.ToTable("tbl_parcel_info");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_parcel_items", b =>
                {
                    b.Property<int>("idtbl_parcel_items")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("tbl_items_sku_id")
                        .HasColumnType("int");

                    b.Property<int>("tbl_parcel_items_info_id")
                        .HasColumnType("int");

                    b.Property<byte>("tbl_parcel_items_parcelDangerousGoods")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("tbl_parcel_items_parcelDescription")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("tbl_parcel_items_parcelDimensionUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_parcel_items_parcelHeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tbl_parcel_items_parcelLength")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("tbl_parcel_items_parcelQty")
                        .HasColumnType("int");

                    b.Property<string>("tbl_parcel_items_parcelReference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_parcel_items_parcelType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_parcel_items_parcelWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_parcel_items_parcelWeightUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_parcel_items_parcelWidth")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("idtbl_parcel_items");

                    b.HasIndex("tbl_items_sku_id");

                    b.HasIndex("tbl_parcel_items_info_id");

                    b.ToTable("tbl_parcel_items");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_receptacle", b =>
                {
                    b.Property<int>("idtbl_receptacle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("tbl_hawb_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("tbl_receptacle_creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_receptacle_dest")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_receptacle_height")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tbl_receptacle_length")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tbl_receptacle_mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("tbl_receptacle_no_items")
                        .HasColumnType("int");

                    b.Property<string>("tbl_receptacle_origin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_receptacle_ref")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_receptacle_shipper_id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_receptacle_status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_receptacle_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("tbl_receptacle_weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tbl_receptacle_width")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("idtbl_receptacle");

                    b.HasIndex("tbl_hawb_id");

                    b.ToTable("tbl_receptacle");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_routing", b =>
                {
                    b.Property<int>("idtbl_routing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("tbl_routing_cutoffDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("tbl_voyage_ata")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("tbl_voyage_atd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_voyage_dischargePort")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("tbl_voyage_eta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("tbl_voyage_etd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("tbl_voyage_id")
                        .HasColumnType("int");

                    b.Property<string>("tbl_voyage_loadPort")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("idtbl_routing");

                    b.HasIndex("tbl_voyage_id");

                    b.ToTable("tbl_routing");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_voyage", b =>
                {
                    b.Property<int>("idtbl_voyage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tbl_voyage_aircrafType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_voyage_aircraftReg")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("tbl_voyage_ata")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("tbl_voyage_atd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_voyage_dischargePort")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("tbl_voyage_eta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("tbl_voyage_etd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tbl_voyage_loadPort")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("tbl_voyage_number")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_voyage_vessel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tbl_voyage_vinNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("idtbl_voyage");

                    b.ToTable("tbl_voyage");
                });

            modelBuilder.Entity("tbl_client_contact_detailstbl_client_contact_group", b =>
                {
                    b.Property<int>("contactDetailsidtbl_client_contact_details")
                        .HasColumnType("int");

                    b.Property<int>("contactGroupsidtbl_client_contact_group")
                        .HasColumnType("int");

                    b.HasKey("contactDetailsidtbl_client_contact_details", "contactGroupsidtbl_client_contact_group");

                    b.HasIndex("contactGroupsidtbl_client_contact_group");

                    b.ToTable("tbl_client_contact_detailstbl_client_contact_group");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_contact_details", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_client_header", "tbl_client_header")
                        .WithMany("contactDetails")
                        .HasForeignKey("tbl_client_header_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbl_client_header");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_header", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_hawb", "tbl_hawb")
                        .WithMany("clientHeaders")
                        .HasForeignKey("tbl_hawb_id");

                    b.HasOne("BTAS.Data.Models.tbl_hawb_incoterms", "tbl_hawb_incoterms")
                        .WithMany()
                        .HasForeignKey("tbl_hawb_incoterms_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAS.Data.Models.tbl_mawb", "mawbCarrier")
                        .WithMany()
                        .HasForeignKey("tbl_mawb_carrier_id");

                    b.HasOne("BTAS.Data.Models.tbl_mawb", "mawbCreditor")
                        .WithMany()
                        .HasForeignKey("tbl_mawb_creditor_id");

                    b.HasOne("BTAS.Data.Models.tbl_mawb", "mawbDestination")
                        .WithMany()
                        .HasForeignKey("tbl_mawb_destination_id");

                    b.HasOne("BTAS.Data.Models.tbl_mawb", "mawbOrigin")
                        .WithMany()
                        .HasForeignKey("tbl_mawb_origin_id");

                    b.Navigation("mawbCarrier");

                    b.Navigation("mawbCreditor");

                    b.Navigation("mawbDestination");

                    b.Navigation("mawbOrigin");

                    b.Navigation("tbl_hawb");

                    b.Navigation("tbl_hawb_incoterms");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_container", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_mawb", "tbl_mawb")
                        .WithMany("containers")
                        .HasForeignKey("tbl_mawb_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbl_mawb");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_container", "tbl_container")
                        .WithMany("hawbs")
                        .HasForeignKey("tbl_container_id");

                    b.HasOne("BTAS.Data.Models.tbl_hawb_incoterms", "tbl_hawb_incoterms")
                        .WithMany()
                        .HasForeignKey("tbl_hawb_incoterms_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAS.Data.Models.tbl_mawb", "mawb")
                        .WithMany("hawbs")
                        .HasForeignKey("tbl_mawb_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mawb");

                    b.Navigation("tbl_container");

                    b.Navigation("tbl_hawb_incoterms");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb_items", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_hawb", "hawb")
                        .WithMany("hawbItems")
                        .HasForeignKey("tbl_hawb_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hawb");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_mawb", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_voyage", "voyage")
                        .WithMany()
                        .HasForeignKey("tbl_mawb_voyage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("voyage");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_parcel_info", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_receptacle", "receptacle")
                        .WithMany("parcelInfos")
                        .HasForeignKey("tbl_receptacle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("receptacle");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_parcel_items", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_items_sku", "tbl_items_sku")
                        .WithMany()
                        .HasForeignKey("tbl_items_sku_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAS.Data.Models.tbl_parcel_info", "tbl_parcel_info")
                        .WithMany("parcelItems")
                        .HasForeignKey("tbl_parcel_items_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbl_items_sku");

                    b.Navigation("tbl_parcel_info");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_receptacle", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_hawb", "tbl_hawb")
                        .WithMany("receptacles")
                        .HasForeignKey("tbl_hawb_id");

                    b.Navigation("tbl_hawb");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_routing", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_voyage", "voyage")
                        .WithMany()
                        .HasForeignKey("tbl_voyage_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("voyage");
                });

            modelBuilder.Entity("tbl_client_contact_detailstbl_client_contact_group", b =>
                {
                    b.HasOne("BTAS.Data.Models.tbl_client_contact_details", null)
                        .WithMany()
                        .HasForeignKey("contactDetailsidtbl_client_contact_details")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTAS.Data.Models.tbl_client_contact_group", null)
                        .WithMany()
                        .HasForeignKey("contactGroupsidtbl_client_contact_group")
                        .HasConstraintName("FK_tbl_client_contact_detailstbl_client_contact_group_tbl_clie~1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_client_header", b =>
                {
                    b.Navigation("contactDetails");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_container", b =>
                {
                    b.Navigation("hawbs");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_hawb", b =>
                {
                    b.Navigation("clientHeaders");

                    b.Navigation("hawbItems");

                    b.Navigation("receptacles");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_mawb", b =>
                {
                    b.Navigation("containers");

                    b.Navigation("hawbs");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_parcel_info", b =>
                {
                    b.Navigation("parcelItems");
                });

            modelBuilder.Entity("BTAS.Data.Models.tbl_receptacle", b =>
                {
                    b.Navigation("parcelInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
